name: Deploy Build Content to Deploy Branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create or update deploy branch
        run: |
          git checkout -B deploy
          git push origin deploy

      - name: Copy build content to deploy
        run: |
          mkdir -p deploy
          cp -r build/* deploy/
          git add deploy
          git commit -m "Update deploy branch"
          git push origin deploy
